# This is configuration file
title: Apps
description: 
theme: 
markdown: kramdown
highlighter: rouge
#markdown: GFM
#markdown: CommonMarkGhPages
#commonmark:
#  options: ["SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "tables"]
# baseurl: 
timezone: Europe/Kiev
plugins:
  - jekyll-redirect-from
  - jemoji
  - jekyll-paginate
  - jekyll-gist

kramdown:
  parse_span_html: true
  parse_block_html: true
timezone: Europe/Kiev

defaults:
- scope:
    type: pages
  values:
    layout: default
