# This is configuration file
title: Apps
description: 
#theme: 
markdown: kramdown
highlighter: rouge
url: ""
baseurl: ""
timezone: Europe/Kiev
plugins:
  - jekyll-redirect-from
  - jemoji
  - jekyll-paginate
  - jekyll-gist

kramdown:
  parse_span_html: true
  parse_block_html: true


